### ISSUE TITLE
Access key of Machine Learning is incorrect when service is bound to an app.

### ISSUE THREAD

**Issue by lionelmace** [pmservice/drug-selection#1]
I successfully deployed this sample.

When hardcoding both the defaultBaseURL and defaultAccessKey values in the app.js, it works fine. Yet, when binding the Machine Learning to the app, the generated credentials, especially the accessKey is incorrect, the score funtion cannot be called and the app does not work. 

Have you faced the same issue?

**Comment by yoowoo** [comment]
Don't understand the scenario, are you trying to run the application locally?

**Comment by yoowoo** [comment]
@lionelmace I wonder if it might be connected to [this issue](https://github.com/pmservice/drug-selection/issues/2). What is the original Bluemix service url you need to modify?

**Comment by lionelmace** [comment]
Yes I'm trying to run the app locally. @yoowoo

**Comment by lionelmace** [comment]
I forked the project and use cfenv module to bind the credentials. It runs fine locally now. The result is here. https://github.com/lionelmace/drug-selection @yoowoo

**Comment by yoowoo** [comment]
@lionelmace thanks for the project, but still I cannot reproduce the issue. Anyway, I've pulled and slightly modified your project under _cfenv_ branch, but since docs refer to different code, the _master_ branch has to wait.
