### ISSUE TITLE
404  error, end point needs to be corrected

### ISSUE THREAD

**Issue by niteshthakrar** [pmservice/drug-selection#2]
Line 76 in app.js needs to be
var scoreURI = env.baseURL + '/score/' + req.body.context + '?accesskey=' + env.accessKey;

**Comment by yoowoo** [comment]
Hi @niteshthakrar, could you please paste the WML service **url** property from the bluemix service credentials? I'm expecting 

> "url": "https://ibm-watson-ml.mybluemix.net"

 which needs to be followed by _/pm/v1/_, as described [here](https://console.ng.bluemix.net/docs/services/PredictiveModeling/pm_service_api_develop.html#pm_service_api_develop__dev1)

**Comment by niteshthakrar** [comment]
Hi,

The url I have (from Bluemix credentials and that works is): 
https://palblyp.pmservice.ibmcloud.com/pm/v1 

So I guess the Credentials now include the pm/v1 which it might not have 
in the past!! 

Thanks,

Nitesh


Best Regards



Nitesh P Thakrar
 

IBM Digital Business Group
 
Developer Ecosystem and Startups
 

 

Mobile:
+33 (0)6 29 22 17 81 
21, av. Simone Veil

e-mail:
nitesh@fr.ibm.com 
ZAC Nice Méridia


@niteshpthakrar
https://my-dbg-guru.mybluemix.net 
06200 Nice, France

**Comment by yoowoo** [comment]
Thanks for a quick response. Was this instance ordered recently?

**Comment by niteshthakrar** [comment]
Yes last week (Wednesday, 19th). 

Best Regards



Nitesh P Thakrar
 

IBM Digital Business Group
 
Developer Ecosystem and Startups
 

 

Mobile:
+33 (0)6 29 22 17 81 
21, av. Simone Veil

e-mail:
nitesh@fr.ibm.com 
ZAC Nice Méridia


@niteshpthakrar
https://my-dbg-guru.mybluemix.net 
06200 Nice, France

**Comment by yoowoo** [comment]
The _url_ will probably change with time, but until that, the code need to be modified to handle the differences between Bluemix regions. Thanks for opening and pinpointing the issue.

**Comment by yoowoo** [comment]
Please give it another try...
