### ISSUE TITLE
Unable to make the app running ok

### ISSUE THREAD

**Issue by PhilippeComte** [pmservice/drug-selection#4]
Hello
The app deploys and I get the screen where I can give the details about the patient  I want to score.
However when I click score I get an error saying that the app cannot find the model.
here it is :
Failed to score drug1N, msg=Can not find model:eu-gb$90c9c2c0-848d-4580-905d-9e2cfa466680/drug1N, details:java.lang.RuntimeException: Can not find model:eu-gb$90c9c2c0-848d-4580-905d-9e2cfa466680/drug1N at com.ibm.spss.internal.scorer.pool.ScorerPoolImpl.get(ScorerPoolImpl.java:96) at com.ibm.spss.blackbox.score.resource.ScoreUtil.score(ScoreUtil.java:191) at com.ibm.spss.blackbox.score.resource.ScoreResource.scoreWithInputdata(ScoreResource.java:69) at 

I have added the model Drug1n.str thru the service dashboard 
I have modified the app.js file with my credentials
var defaultBaseURL = 'https://palblyp.pmservice.ibmcloud.com/pm/v1';
var defaultAccessKey = '====EbjWYrA472TtheuyABbgmIv4Gf3OM3oS964AoaiK9b6iNjiik+2n997pvelDBj2EWArRQzCnErs5G6xF7OPG2R5H0oB=====';

Can you help ? 
Thank you very much

**Comment by PhilippeComte** [comment]
Following the read.me notice about the context.id name, everything runs ok 
Why is the context id so specific ?  is it referenced in the app somewhere  ? 

Prerequisites

Model available in \model subdirectory (Drug1n.str) has to be uploaded to the Watson Machine Learning instance using Dashboard (drop box). Make sure that uploaded model is named correctly (contextID=drug1N).

Drug1n.str --> drug1N

**Comment by yoowoo** [comment]
@PhilippeComte the _Context Id_ is hardcoded in [_public\js\app.js_](https://github.com/pmservice/drug-selection/blob/master/public/js/app.js)
